import { useMemo, useState } from "react";
import { useCatalog } from "../context/CatalogContext";
import { useAuth } from "../context/AuthContext";
import { orders as seedOrders } from "../data/orders";
import Alert from "../components/common/Alert";

const blank={name:"",description:"",price:"",stockQuantity:"",category:"Accessories",image:"/images/product.svg",isActive:true};
function AdminPage(){
 const {products,categories,saveProduct,toggleProduct,saveCategory}=useCatalog(); const {users}=useAuth(); const [tab,setTab]=useState("products"); const [query,setQuery]=useState(""); const [edit,setEdit]=useState(null); const [form,setForm]=useState(blank); const [notice,setNotice]=useState("");
 const [orders,setOrders]=useState(()=>{try{return JSON.parse(localStorage.getItem("ecommerce_orders"))||seedOrders}catch{return seedOrders}});
 const filtered=useMemo(()=>products.filter((product)=>product.name.toLowerCase().includes(query.toLowerCase())),[products,query]);
 const save=(event)=>{event.preventDefault(); if(!form.name.trim()||!form.price)return; saveProduct({...form,id:edit?.id});setForm(blank);setEdit(null);setNotice("Product saved successfully.");};
 const status=(id,value)=>setOrders((items)=>{const next=items.map((order)=>order.id===id?{...order,status:value}:order);localStorage.setItem("ecommerce_orders",JSON.stringify(next));return next;});
 const sales=orders.reduce((total,order)=>total+Number(order.total||0),0);
 return <main className="container page-section"><h1>Admin Dashboard</h1>{notice&&<Alert type="success">{notice}</Alert>}<div className="admin-layout"><aside className="admin-sidebar"><button onClick={()=>setTab("products")}>Products</button><button onClick={()=>setTab("categories")}>Categories</button><button onClick={()=>setTab("orders")}>Orders</button></aside><section><div className="admin-grid"><article className="admin-card"><strong>Users</strong><p>{users.length}</p></article><article className="admin-card"><strong>Products</strong><p>{products.length}</p></article><article className="admin-card"><strong>Orders</strong><p>{orders.length}</p></article><article className="admin-card"><strong>Total Sales</strong><p>${sales.toFixed(2)}</p></article></div>
 {tab==="products"&&<><h2>Product Management</h2><input aria-label="Search products" placeholder="Search products" value={query} onChange={(e)=>setQuery(e.target.value)}/><form className="admin-form" onSubmit={save}><label>Name<input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label>Category<select value={form.category} onChange={(e)=>setForm({...form,category:e.target.value})}>{categories.map((category)=><option key={category.id}>{category.name}</option>)}</select></label><label>Price<input type="number" min="0" value={form.price} onChange={(e)=>setForm({...form,price:e.target.value})}/></label><label>Stock<input type="number" min="0" value={form.stockQuantity} onChange={(e)=>setForm({...form,stockQuantity:e.target.value})}/></label><label>Description<input value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><button className="btn btn--primary">{edit?"Save Changes":"Add Demo Product"}</button></form>{filtered.map((product)=><article className="admin-product" key={product.id}><div><strong>{product.name}</strong><p>{product.category} · ${product.price} · Stock: {product.stockQuantity} · {product.isActive?"Active":"Disabled"}</p></div><div><button onClick={()=>{setEdit(product);setForm(product)}}>Edit</button><button onClick={()=>toggleProduct(product.id)}>{product.isActive?"Disable":"Enable"}</button></div></article>)}</>}
 {tab==="categories"&&<><h2>Categories</h2>{categories.map((category)=><article className="admin-product" key={category.id}><strong>{category.name}</strong><span>{category.description}</span></article>)}<form className="admin-form" onSubmit={(e)=>{e.preventDefault();const name=e.target.category.value.trim();if(name){saveCategory({name,description:"Locally managed category.",image:"/images/product.svg"});e.target.reset();}}}><label>Add Category<input name="category"/></label><button className="btn btn--primary">Add Category</button></form></>}
 {tab==="orders"&&<><h2>Orders</h2>{orders.map((order)=><article className="admin-product" key={order.id}><div><strong>{order.id}</strong><p>{order.customer?.fullName||order.customerName||"Demo Customer"} · ${Number(order.total).toFixed(2)}</p></div><label>Status<select value={order.status} onChange={(e)=>status(order.id,e.target.value)}>{["Pending","Processing","Shipped","Delivered","Cancelled","pending"].map((item)=><option key={item}>{item}</option>)}</select></label></article>)}</>}
 </section></div></main>;
}
export default AdminPage;
